issue_tracker:
  config:
    api_token: ''
    base_url: ''
    email: ''
    project_key: ''
  platform: ''
llm:
  config:
    api_key: ''
  type: openai
repo:
  config:
    token: ''
    url: ''
  platform: bitbucket
